[package]
name = "scene3d-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy-inspector-egui.workspace = true
bevy_framepace.workspace = true
avian3d.workspace = true

core.workspace = true